### ISSUE TITLE
Crear formulario para registrar usuarios

### ISSUE THREAD

**Issue by VillenaFranco** [CachaSan10/TP_FINAL_2023-PV#11]
Se creara formulario en nuevo_usuario.html para registrar usuarios.

**Comment by CachaSan10** [comment]
Esquema de la pagina web de registrar usuarios.
![REGISTRARME](https://github.com/CachaSan10/TP_FINAL_2023-PV/assets/97699992/40f98aaa-8b8d-4bf3-856f-d77fd0cd1df0)
